#! /usr/bin/env python
# -*- coding: utf-8 -*-
#/usr/bin/python2.4 -u

import os
import commands 
import unittest

class csv_extents_test( unittest.TestCase ) :
    def ascii( self, input, result, commandString ) :
        f = open('/tmp/extents.csv', 'w')
        f.writelines( input )
        f.close()
        self.assertEquals( commands.getstatusoutput( "cat /tmp/extents.csv | " + commandString )[1].split(), result )

    def binary( self, input, result, inputFormat, outputFormat, commandString ) :
        f = open('/tmp/extents.csv', 'w')
        f.writelines( input )
        f.close()
        os.system( "cat /tmp/extents.csv | csv-to-bin " + inputFormat + " > /tmp/extents.bin" )
        self.assertEquals( commands.getstatusoutput( "cat /tmp/extents.bin | " + commandString + " | csv-from-bin " + outputFormat )[1].split(), result )
    
    def test_basics( self ) :
        input = ['1,2,3']
        result = ["1,2,3,1,2,3"]
        self.ascii( input, result, "csv-extents " )
        self.binary( input, result, "3d", "6d",   "csv-extents --binary 3d " )

        input = ['1,2,3\n', "4,5,6\n"]
        result = ["1,2,3,4,5,6"]
        self.ascii( input, result, "csv-extents " )
        self.binary( input, result, "3d", "6d",   "csv-extents --binary 3d " )

        input = ['1\n', "2\n"]
        result = ["1,2"]
        self.ascii( input, result, "csv-extents " )
        self.binary( input, result, "d", "2d",   "csv-extents --binary d " )

        input = [ "20110110T010000,1,0,-1,0,101,0,1\n" \
                 ,"20110110T110000,11,0,-11,0,201,1,1\n" \
                 ,"20110110T020000,2,0,-2,0,103,0,1\n" \
                 ,"20110110T030000,3,0,-3,0,102,0,1\n" \
                 ,"20110110T120000,12,0,-12,0,203,1,2\n" \
                 ,"20110110T130000,13,0,-13,0,202,1,2\n"]
        result = [ "20110110T010000,1,0,-13,0,101,0,1,20110110T130000,13,0,-1,0,203,1,2" ]
        self.ascii( input, result, "csv-extents " )
        self.binary( input, result, "t,d,ui,2d,3ui", "t,d,ui,2d,3ui,t,d,ui,2d,3ui", "csv-extents --binary t,d,ui,2d,3ui " )
        
        result = [ "20110110T010000,1,0,-3,0,101,20110110T030000,3,0,-1,0,103,0,1" \
                 , "20110110T110000,11,0,-11,0,201,20110110T110000,11,0,-11,0,201,1,1" \
                 , "20110110T120000,12,0,-13,0,202,20110110T130000,13,0,-12,0,203,1,2" ]
        self.ascii( input, result, "csv-extents  --format t,d,ui,2d,3ui --fields t,x,a,y,z,b,id,block" )
        self.binary( input, result, "t,d,ui,2d,3ui", "t,d,ui,2d,ui,t,d,ui,2d,3ui", "csv-extents --binary t,d,ui,2d,3ui --fields t,x,a,y,z,b,id,block " )

unittest.main()

