#! /usr/bin/env python
# -*- coding: utf-8 -*-
#/usr/bin/python2.4 -u

import commands # watch deprecated: see subprocess module doc
import unittest 

class csv_time_test( unittest.TestCase ) :
    def test_basics( self ) :
        self.assertNotEqual( commands.getstatusoutput( "echo blah | csv-time --to-iso-string" )[0], 0 )
        self.assertEquals( float( commands.getstatusoutput( "echo 0 | csv-time --to-iso-string | csv-time --to-seconds" )[1] ), 0 )
        self.assertEquals( float( commands.getstatusoutput( "echo 1.234 | csv-time --to-iso-string | csv-time --to-seconds" )[1] ), 1.234 )    

unittest.main()

